### ISSUE TITLE
Testing With Q Installed

### ISSUE THREAD

**Issue by yznima** [sv/kdbgo#12]
I am thinking of addressing the `installing q is in your future` to install Q on Travis CI since I believe some of the tests are failing when run with Q installed on my machine

I was thinking we could check in the 32 bit binary of Q into the repository and run that. Do you have any approach in mind?

**Comment by yznima** [comment]
@sv What do you think about this?

**Comment by sv** [comment]
Terms and conditions of 32bit don't allow checking in binary into public repo.
Maybe same approach that is used in https://github.com/KxSystems/pyq/blob/master/.travis/getkdb.sh can be used in other repos. `go test` would start q if it is in your path locally to test.

**Comment by yznima** [comment]
Sounds great. I will try to see If I can get it working

**Comment by yznima** [comment]
@sv Looks like in the line `curl -O https://kx.com/$X/3.5/linuxx86.zip` X is set outside the repository. Is this something that can be set by you?

**Comment by sv** [comment]
@yznima  added

**Comment by yznima** [comment]
@sv It doesn't seem like the value of $X is present. See the logs in https://travis-ci.org/sv/kdbgo/jobs/513282026 for the `curl` command. The value is empty

**Comment by sv** [comment]
It would work only when built from sv/kdbgo repo. You would need to setup the same if you want to test your branches. To get value of X you need to register and agree to terms of service for 32bit and extract X from link you get for Linux. 
Then in your travis setup, add it to environment variables and tick 'hide from console' box.
