### ISSUE TITLE
wrong cast to string in DialKDBTimeout

### ISSUE THREAD

**Issue by ktye** [sv/kdbgo#18]
In https://github.com/sv/kdbgo/blob/master/kdb.go#L208 the port, which is an int value is casted to a string by `string(port)`.
This is not correct.
Consider using `strconv.Itoa(port)` or fmt.Sprintf.

**Comment by sv** [comment]
This is non-issue in https://github.com/sv/kdbgo/blob/v1beta/kdb.go branch. Will fix in current

**Comment by sv** [comment]
fixed in https://github.com/sv/kdbgo/commit/588f574a29a2f1456de0505b063ccdcc535e3208
