### ISSUE TITLE
panic: github.com/sv/kdbgo/kdb.go:85 +0x179

### ISSUE THREAD

**Issue by a7a2** [sv/kdbgo#5]
panic: runtime error: slice bounds out of range

goroutine 162 [running]:
bufio.(*Reader).Read(0xc4202181e0, 0xc4216b5c88, 0x8, 0x8, 0x8, 0x16c96e0, 0x0)
	/usr/local/go/src/bufio/bufio.go:227 +0x3bf
io.ReadAtLeast(0x1888be0, 0xc4202181e0, 0xc4216b5c88, 0x8, 0x8, 0x8, 0x16c9760, 0x1767701, 0xc4216b5c88)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x1888be0, 0xc4202181e0, 0xc4216b5c88, 0x8, 0x8, 0x8, 0xc420036f00, 0xc420070218)
	/usr/local/go/src/io/io.go:327 +0x58
encoding/binary.Read(0x1888be0, 0xc4202181e0, 0x1890300, 0x1cb5b00, 0x1708000, 0xc4216b5348, 0xc420704380, 0xc4216efad0)
	/usr/local/go/src/encoding/binary/binary.go:245 +0xf48
github.com/sv/kdbgo.Decode(0xc4202181e0, 0xc420222028, 0x1, 0xc421213f40, 0x0)
	/github.com/sv/kdbgo/decode.go:141 +0x95
github.com/sv/kdbgo.(*KDBConn).Call(0xc4201e2230, 0xc424473dc0, 0x3d, 0x0, 0x0, 0x0, 0xc42000e018, 0xc420e1bed8, 0x1)
	/github.com/sv/kdbgo/kdb.go:85 +0x179

**Comment by sv** [comment]
do you have reproducer? which version of kdbgo, go, kdb+ is that?

**Comment by a7a2** [comment]
go version go1.10 darwin/amd64.
kdb+ is  the last one.

maybe no header,I call like this:
_, err = conn.Call("`data insert (2018.04.04T21:17:48z;`AUS200;5721e;5725.1e)")

and sometimes get
 "_, err = conn.Call("data:([]date:`datetime$();sym:`symbol$();bid:`real$();ask:`real$())")"

**Comment by a7a2** [comment]
go version go1.10 darwin/amd64.
kdb+ is the last one.

maybe no header,I call like this:
_, err = conn.Call("data insert (2018.04.04T21:17:48z;`AUS200;5721e;5725.1e)")

and sometimes get
"_, err = conn.Call("data:([]date:datetime$();sym:symbol$();bid:real$();ask:real$())")"

**Comment by a7a2** [comment]
go version go1.10 darwin/amd64.
kdb+ is the last one.

maybe no header,I call like this:
_, err = conn.Call("data insert (2018.04.04T21:17:48z;`AUS200;5721e;5725.1e)")

and sometimes get error like this:
"kdb+ Query failed: header is invalid    `data insert (2018.04.04T21:17:48z;`AUS200;5721e;5725.1e)"

**Comment by a7a2** [comment]
reproducer:
`package main

import (
	"fmt"

	"github.com/sv/kdbgo"
)

var conn *kdb.KDBConn

func init() {
	var err error
	conn, err = kdb.DialKDB("127.0.0.1", 9999, "")
	if err != nil {
		fmt.Println("Failed to connect:", err)
		return
	}
	_, err = conn.Call("data:([]date:`datetime$();sym:`symbol$();bid:`real$();ask:`real$())")
	if err != nil {
		fmt.Println("Query failed:", err)
	}
}

func main() {
	for {
		go func() {
			res, err := conn.Call("`data insert (2018.04.04T22:07:59z;`XOM.NYSE;74e;74.01e)")
			if err != nil {
				fmt.Println("Query failed:", err)
			}
			fmt.Println("Result:", res)
		}()
	}

}
`

**Comment by sv** [comment]
Is it still an issue? I see that you closed it now

**Comment by a7a2** [comment]
I don't know much about the rules of the GitHub，temporary fix use by ‘sync.lock’。
I need to write code for my project, which will not waste too more time to understand it.

**Comment by sv** [comment]
I see. Why do you need to insert from infinite number of goroutines? It
will be in random order anyway.
It is not designed to be used that way - you can have finite number of
goroutines(1000) each one with own connection.
There is no internal queue of messages inside library

**Comment by a7a2** [comment]
I just recur the problem. In the actual project ,I just collect forex data to kdb+ and then expose this issue.
There is a need to use ‘go’ in the actual project.
For example：The kdb+ server is so far away and the network delay > 500ms,blocked network.
Do not use channel to solve the problem as much as possible.
